// The Data for dashboard
const myApplications = [
    { company: "Google", role: "UX Designer", date: "2025-04-01", status: "Interviewing", industry: "Technology" },
    { company: "Petronas", role: "Data Analyst", date: "2025-04-02", status: "Applied", industry: "Oil & Gas" },
    { company: "Shopee", role: "Frontend Dev", date: "2025-04-05", status: "Rejected", industry: "Technology" },
    { company: "Maybank", role: "FinTech Intern", date: "2025-04-07", status: "Offer Received", industry: "Finance" },
    { company: "Grab", role: "Product Designer", date: "2025-04-10", status: "Interviewing", industry: "Technology" },
    { company: "Shell", role: "Process Engineer", date: "2025-04-12", status: "Applied", industry: "Oil & Gas" },
    { company: "Intel", role: "Hardware Engineer", date: "2025-04-15", status: "Applied", industry: "Technology" },
    { company: "Maxis", role: "Network Engineer", date: "2025-04-18", status: "Applied", industry: "Technology" },
    { company: "CIMB Bank", role: "Investment Intern", date: "2025-04-20", status: "Interviewing", industry: "Finance" },
    { company: "Axiata", role: "Cloud Architect", date: "2025-04-22", status: "Applied", industry: "Technology" },
    { company: "Sime Darby", role: "HR Analyst", date: "2025-04-25", status: "Applied", industry: "Manufacturing" },
    { company: "AirAsia", role: "Mobile Developer", date: "2025-04-28", status: "Rejected", industry: "Technology" },
    { company: "Public Bank", role: "Credit Analyst", date: "2025-05-01", status: "Offer Received", industry: "Finance" },
    { company: "Top Glove", role: "QA Engineer", date: "2025-05-03", status: "Applied", industry: "Manufacturing" },
    { company: "TM (Telekom)", role: "Cybersecurity", date: "2025-05-05", status: "Interviewing", industry: "Technology" },
    { company: "PwC", role: "Audit Intern", date: "2025-05-07", status: "Applied", industry: "Finance" },
    { company: "EY Malaysia", role: "Tax Consultant", date: "2025-05-10", status: "Applied", industry: "Finance" },
    { company: "Nestlé", role: "Supply Chain", date: "2025-05-12", status: "Applied", industry: "Manufacturing" },
    { company: "Microsoft", role: "AI Research", date: "2025-05-15", status: "Interviewing", industry: "Technology" },
    { company: "IBM", role: "Backend Developer", date: "2025-05-18", status: "Rejected", industry: "Technology" },
    { company: "Standard Chartered", role: "DevOps", date: "2025-05-20", status: "Offer Received", industry: "Finance" },
    { company: "Tencent", role: "Game Developer", date: "2025-05-22", status: "Applied", industry: "Technology" },
    { company: "ExxonMobil", role: "Safety Engineer", date: "2025-05-25", status: "Applied", industry: "Oil & Gas" },
    { company: "Samsung", role: "Mobile Intern", date: "2025-05-28", status: "Applied", industry: "Technology" },
    { company: "Amazon", role: "AWS Intern", date: "2025-06-01", status: "Interviewing", industry: "Technology" },
    { company: "Deloitte", role: "Risk Advisory", date: "2025-06-03", status: "Applied", industry: "Finance" },
    { company: "Lazada", role: "Marketing Intern", date: "2025-06-05", status: "Rejected", industry: "Technology" },
    { company: "Bursa Malaysia", role: "Data Scientist", date: "2025-06-08", status: "Applied", industry: "Finance" }
];